### ISSUE TITLE
Keyboard forced close

### ISSUE THREAD

**Issue by kuntau** [SeventhM/hackerskeyboard#7]
**Describe the bug**
If if you press `fn` the second time, then it doesn't go back to normal layout instead it forced close 

**To Reproduce**
1. Tap `fn` twice in a row
2. It will forced close

**Expected behavior**
Keyboard go back to normal layout 

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: Poco F3
 - OS: Android 13
 - App version `1.41.1`

**Additional context**
I'm using portrait 5 row layout

**Comment by redyoshi49q** [comment]
I have this issue, too.  This is a section of adb logs that I was able to get from the crash:

<details>
<summary>It's a bit of a long one.</summary>

```
08-02 21:10:32.100  6002  6002 E InputEventReceiver: Exception dispatching input event.
08-02 21:10:32.100  6002  6002 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: java.lang.NullPointerException
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView.setMetaIndicator(LatinKeyboardBaseView.kt:674)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at org.pocketworkstation.pckeyboard.KeyboardSwitcher.setMetaIndicator(KeyboardSwitcher.kt:377)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at org.pocketworkstation.pckeyboard.LatinIME.setModFn(LatinIME.kt:2004)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at org.pocketworkstation.pckeyboard.LatinIME.onPress(LatinIME.kt:2931)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at org.pocketworkstation.pckeyboard.PointerTracker.onDownEvent(PointerTracker.kt:236)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView.onDownEvent(LatinKeyboardBaseView.kt:1662)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView.onTouchEvent(LatinKeyboardBaseView.kt:1641)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView.onTouchEvent(LatinKeyboardBaseView.kt:1545)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at org.pocketworkstation.pckeyboard.LatinKeyboardView.onTouchEvent(LatinKeyboardView.kt:252)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.View.dispatchTouchEvent(View.java:15076)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1015)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1962)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.app.Dialog.dispatchTouchEvent(Dialog.java:1264)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:192)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:973)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.View.dispatchPointerEvent(View.java:15335)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7815)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7588)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6922)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7143)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7200)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10400)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10248)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10204)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10532)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.os.MessageQueue.nativePollOnce(Native Method)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.os.MessageQueue.next(MessageQueue.java:335)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.os.Looper.loopOnce(Looper.java:186)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.os.Looper.loop(Looper.java:313)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at java.lang.reflect.Method.invoke(Native Method)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
08-02 21:10:32.101  6002  6002 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: FATAL EXCEPTION: main
08-02 21:10:32.104  6002  6002 E AndroidRuntime: Process: org.pocketworkstation.pckeyboard, PID: 6002
08-02 21:10:32.104  6002  6002 E AndroidRuntime: java.lang.NullPointerException
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView.setMetaIndicator(LatinKeyboardBaseView.kt:674)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at org.pocketworkstation.pckeyboard.KeyboardSwitcher.setMetaIndicator(KeyboardSwitcher.kt:377)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at org.pocketworkstation.pckeyboard.LatinIME.setModFn(LatinIME.kt:2004)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at org.pocketworkstation.pckeyboard.LatinIME.onPress(LatinIME.kt:2931)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at org.pocketworkstation.pckeyboard.PointerTracker.onDownEvent(PointerTracker.kt:236)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView.onDownEvent(LatinKeyboardBaseView.kt:1662)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView.onTouchEvent(LatinKeyboardBaseView.kt:1641)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at org.pocketworkstation.pckeyboard.LatinKeyboardBaseView.onTouchEvent(LatinKeyboardBaseView.kt:1545)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at org.pocketworkstation.pckeyboard.LatinKeyboardView.onTouchEvent(LatinKeyboardView.kt:252)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:15076)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1015)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1962)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.app.Dialog.dispatchTouchEvent(Dialog.java:1264)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:192)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:973)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:15335)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7815)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7588)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6922)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7143)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7200)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10400)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10248)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10204)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10532)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:335)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:186)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
08-02 21:10:32.104  6002  6002 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

</details>

I don't have a build environment set up, but it /looks/ like the problem might be addressed by removing the second "!!" in line 674 of LatinKeyboardBaseView.kt.  The null pointer exception couldn't have been triggered by the first "!!" (mKeyboard was already checked to not be null), and given that invalidateKey can accept a null input value (in which case it just returns without doing anything), it should be fine for setMetaIndicator to return null; no check should be needed there.  The fact that the setMetaIndicator function allowed for a void return value in the old Java code (before the conversion to Kotlin) further suggests that it's intended for this function to be able to return a null value (the Kotlin version of setMetaIndicator returns a potentially null Key? variable, which does correspond to what the Java code did).

If that is indeed the issue (and that code change removes the crash without other side effects), then the second "!!" of lines 662 and 668 in the same file should also be removed.  ~~There might also be other function calls to invalidateKey() elsewhere in the code that erroneously perform a null value exception check on the input.~~ (*edit: I apparently temporarily forgot that grep was a thing.  There don't appear to be any other extra null value exception checks to invalidateKey() calls aside from the aforementioned three.*)

**Comment by redyoshi49q** [comment]
I set up a build environment and tried out the aforementioned fix.  It seems to work as expected in the Android Studio emulator; repeatedly tapping the Fn key reproduces the crash before the fix, but no longer causes the crash after the fix.

I've submitted a pull request with this change (I changed all three lines, even though only one seems to be related to this bug; by the same reasoning, the second "!!" is problematic in all three instances).
